name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to rollback to'
        required: true
        default: 'previous'

jobs:
  rollback:
    name: Rollback to Previous Version
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Rollback ECS service
      run: |
        # Get previous task definition
        TASK_DEF=$(aws ecs describe-services \
          --cluster modern-apache-server-cluster \
          --services modern-apache-server-service \
          --query 'services[0].taskDefinition' \
          --output text)
        
        # Trigger rollback
        aws ecs update-service \
          --cluster modern-apache-server-cluster \
          --service modern-apache-server-service \
          --task-definition $TASK_DEF \
          --force-new-deployment
        
        echo "Rollback initiated"